const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
const root=document.documentElement, nav=document.querySelector('.nav'), bar=document.querySelector('.progress i');
document.getElementById('year').textContent=new Date().getFullYear();
addEventListener('pointermove',e=>{root.style.setProperty('--mx',e.clientX+'px');root.style.setProperty('--my',e.clientY+'px')},{passive:true});
addEventListener('scroll',()=>{const max=document.documentElement.scrollHeight-innerHeight;bar.style.width=(scrollY/max*100)+'%';nav.classList.toggle('scrolled',scrollY>20);document.querySelectorAll('.parallax').forEach(el=>el.style.transform=`translateY(${(el.getBoundingClientRect().top-innerHeight/2)*-.035}px)`)},{passive:true});
const menu=document.querySelector('.menu');menu.addEventListener('click',()=>{const open=nav.classList.toggle('open');menu.setAttribute('aria-expanded',open)});document.querySelectorAll('nav a').forEach(a=>a.onclick=()=>{nav.classList.remove('open');menu.setAttribute('aria-expanded','false')});
const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('seen');io.unobserve(e.target)}}),{threshold:.12});document.querySelectorAll('.reveal').forEach(el=>io.observe(el));
document.querySelector('.summon').addEventListener('click',()=>{document.body.classList.remove('summoned');void document.body.offsetWidth;document.body.classList.add('summoned');setTimeout(()=>document.body.classList.remove('summoned'),1700)});
if(!reduced)document.querySelectorAll('[data-tilt]').forEach(el=>{el.addEventListener('pointermove',e=>{const r=el.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;el.style.transform=`perspective(900px) rotateX(${-y*5}deg) rotateY(${x*7}deg)`});el.addEventListener('pointerleave',()=>el.style.transform='')});
const track=document.querySelector('.archive-track');let down=false,start=0,left=0;track.addEventListener('pointerdown',e=>{down=true;start=e.clientX;left=track.scrollLeft;track.setPointerCapture(e.pointerId)});track.addEventListener('pointermove',e=>{if(down)track.scrollLeft=left-(e.clientX-start)});track.addEventListener('pointerup',()=>down=false);track.addEventListener('keydown',e=>{if(e.key==='ArrowRight')track.scrollBy({left:track.clientWidth*.7,behavior:'smooth'});if(e.key==='ArrowLeft')track.scrollBy({left:-track.clientWidth*.7,behavior:'smooth'})});
if(!reduced){const c=document.getElementById('ether'),x=c.getContext('2d');let w,h,dpr,pts=[];function size(){dpr=Math.min(devicePixelRatio,2);w=innerWidth;h=innerHeight;c.width=w*dpr;c.height=h*dpr;x.setTransform(dpr,0,0,dpr,0,0);pts=Array.from({length:Math.min(70,Math.floor(w/14))},()=>({x:Math.random()*w,y:Math.random()*h,r:Math.random()*1.6+.3,v:Math.random()*.32+.08,a:Math.random()*.6+.15}))}function draw(){x.clearRect(0,0,w,h);for(const p of pts){p.y-=p.v;if(p.y<0){p.y=h;p.x=Math.random()*w}x.beginPath();x.fillStyle=`rgba(84,244,238,${p.a})`;x.shadowBlur=8;x.shadowColor='#54f4ee';x.arc(p.x,p.y,p.r,0,7);x.fill()}requestAnimationFrame(draw)}addEventListener('resize',size);size();draw()}
